export const CHANGE_BANNERS = 'CHANGE_BANNERS'
export const CHANGE_NINEDATA = 'CHANGE_NINEDATA'
export const CHANGE_HOME_INFO = 'CHANGE_HOME_INFO'
export const CHANGE_ARTICLE_INFO = 'CHANGE_ARTICLE_INFO'